<?php

namespace AppBundle\Repository;

/**
 * StageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReceipts($limit)
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select("r")
            ->from('AppBundle:Receipts', 'r');
        if ($limit != "") {
            $qb->setMaxResults($limit);
        } else {
            $qb->setMaxResults(3);
        }
        return $qb->getQuery()->getResult();
    }
}