<?php

namespace AppBundle\Repository;

/**
 * Type_cookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_cookingRepository extends \Doctrine\ORM\EntityRepository
{
}
