<?php

namespace AppBundle\Repository;

/**
 * Type_dishesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_dishesRepository extends \Doctrine\ORM\EntityRepository
{
}
