app:
    resource: '@AppBundle/Controller/'
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


new_receipt:
    path: /new_receipt
    defaults: { _controller: AppBundle:Receipts:add }

receipt:
    path: /receipt
    defaults: { _controller: AppBundle:Receipts:index }

error:
    path: /error
    defaults: { _controller: AppBundle:Error:index }

read_receipt:
    path: /read_receipt
    defaults: { _controller: AppBundle:Receipts:read }

search_receipt:
    path: /search_receipt
    defaults: { _controller: AppBundle:Receipts:searchReceipts }

new:
    path: /new
    defaults: { _controller: AppBundle:New:index }


