app:
    resource: '@AppBundle/Controller/'
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

<<<<<<< HEAD
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    
||||||| parent of 0298ed9... ADDED form
app_home:
    path:      /
    defaults:
        _controller: AppBundle:home:index
=======
app_home:
    path:      /
    defaults:
        _controller: AppBundle:home:index

new_receipt:
    path: /new_receipt
    defaults:
        _controller: AppBundle:Receipts:add
>>>>>>> 0298ed9... ADDED form
